name: "postprocess"
backend: "python"
max_batch_size: 0
input [
  {
    name: "POSTPROCESS_INPUT" 
    data_type: TYPE_FP32
    dims: [1,25500,11]
  }
]
output [
  {
    name: "POSTPROCESSED_OUTPUT" 
    data_type: TYPE_FP32
    dims: [-1,6]
  }
]